---

- block:
  - name: add apt repository
    become: yes
    apt_repository:
      repo: ppa:ubuntu-desktop/ubuntu-make

  - name: install packages
    become: yes
    apt:
      name: ubuntu-make
      state: present
      update_cache: yes
      cache_valid_time: 3600
  when: ansible_distribution == "Ubuntu"
