---

- name: ensure picojson installed
  stat:
    path: /usr/local/src/picojson-{{ picojson_version }}
  register: src_dir

- name: download
  become: yes
  unarchive:
    src: https://github.com/kazuho/picojson/archive/v{{ picojson_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not src_dir.stat.exists

- name: create directory
  become: yes
  file:
    path: /usr/local/stow/picojson-{{ picojson_version }}/include/picojson
    state: directory

- name: copy files
  become: yes
  copy:
    src: /usr/local/src/picojson-{{ picojson_version }}/picojson.h
    dest: /usr/local/stow/picojson-{{ picojson_version }}/include/picojson
    remote_src: yes

- name: stow
  become: yes
  shell: stow -R picojson-{{ picojson_version }}
  args:
    chdir: /usr/local/stow
