---

- name: download
  become: yes
  unarchive:
    src: https://github.com/google/cctz/archive/v{{ cctz_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/cctz-{{ cctz_version }}

- name: compile and install
  become: yes
  shell: "{{ item }}"
  with_items:
    - cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/stow/cctz-{{ cctz_version }} -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_TESTING=OFF .
    - ninja
    - mkdir -p /usr/local/stow/cctz-{{ cctz_version }}/lib
    - cp -rp include /usr/local/stow/cctz-{{ cctz_version }}
    - cp -rp libcctz.a /usr/local/stow/cctz-{{ cctz_version }}/lib
  args:
    chdir: /usr/local/src/cctz-{{ cctz_version }}
    warn: no
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: stow
  become: yes
  shell: stow -R cctz-{{ cctz_version }}
  args:
    chdir: /usr/local/stow
