---

- name: install c++ tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ccache
    - cmake
    - gdb
    - graphviz
    - ninja-build
    - qt5-qtbase-devel
    - valgrind

- name: enable ccache
  become: yes
  file:
    src: /usr/bin/ccache
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - cc
    - c++
    - gcc
    - g++

- name: enable qmake
  become: yes
  file:
    src: /usr/lib64/qt5/bin/qmake
    dest: /usr/local/bin/qmake
    state: link
