---

- name: install ninja
  become: yes
  apt:
    name: ninja-build
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: enable ninja
  become: yes
  file:
    src: /usr/bin/ninja
    dest: /usr/local/bin/ninja
    state: link
