---

- name: ensure downloaded
  stat:
    path: /usr/local/src/spdlog-{{ spdlog_version }}
  register: src_dir

- name: download
  become: yes
  unarchive:
    src: https://github.com/gabime/spdlog/archive/v{{ spdlog_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not src_dir.stat.exists

- name: create directory
  become: yes
  file:
    path: /usr/local/stow/spdlog-{{ spdlog_version }}
    state: directory

- name: install
  become: yes
  command: cp -rp include /usr/local/stow/spdlog-{{ spdlog_version }}
  args:
    chdir: /usr/local/src/spdlog-{{ spdlog_version }}

- name: stow
  become: yes
  shell: stow -R spdlog-{{ spdlog_version }}
  args:
    chdir: /usr/local/stow
