---

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
  when: ansible_distribution_release == "trusty"

#
# FIXME
#
#   Failed to validate the SSL certificate for download.docker.com:443.
#   Make sure your managed systems have a valid CA certificate installed.
#   If the website serving the url uses SNI you need python >= 2.7.9
#   on your managed machine or you can install
#   the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules
#   to perform SNI verification in python >= 2.6.
#
# - name: add apt key
#   become: yes
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     state: present

- name: add apt key
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    warn: no

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | regex_replace('bionic', 'xenial') }} stable
    filename: docker
    state: present
  register: docker_repo

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  when: docker_repo is changed

- name: add user to docker group
  become: yes
  shell: usermod -aG docker "{{ ansible_user_id }}"

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
