---

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual
  when: ansible_distribution_release == "trusty"

- name: add apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  register: docker_repo

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: "{{ docker_repo|changed }}"

- name: add vagrant user to docker group
  become: yes
  shell: usermod -aG docker vagrant
  when: ansible_user_id == "vagrant"
