---

- name: add apt repository
  become: yes
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: install packages
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
    cache_valid_time: 3600
