---

- name: remove /var/crash/*
  become: yes
  file:
    name: /var/crash/*
    state: absent

- name: set timezone
  become: yes
  timezone:
    name: Asia/Tokyo

- name: change ubuntu apt repository
  become: yes
  replace:
    dest: /etc/apt/sources.list
    regexp: 'http://(us\.)?archive\.ubuntu\.com/ubuntu/'
    replace: 'http://linux.yz.yamagata-u.ac.jp/ubuntu/'
  register: ubuntu_repo

- name: add apt key
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg
    - https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg

- name: add apt repository
  become: yes
  get_url:
    url: https://www.ubuntulinux.jp/sources.list.d/{{ ansible_distribution_release }}.list
    dest: /etc/apt/sources.list.d/ubuntu-ja.list
  register: ubuntu_ja_repo

- name: update repositories
  become: yes
  apt:
    update_cache: yes
  when: ubuntu_repo|changed or ubuntu_ja_repo|changed
