---

- name: set timezone
  become: yes
  timezone:
    name: Asia/Tokyo

- name: change ubuntu repository url
  become: yes
  replace:
    dest: /etc/apt/sources.list
    regexp: 'http://(.*\.)?archive\.ubuntu\.com/ubuntu/'
    replace: 'http://ubuntutym.u-toyama.ac.jp/ubuntu/'

- name: add ubuntu japanese team repository
  become: yes
  apt_repository:
    repo: 'ppa:japaneseteam/ppa'

- name: update repositories
  become: yes
  apt:
    update_cache: yes
