---

- name: install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv

- name: install python
  shell: "{{ item }}"
  with_items:
    - pyenv install {{ python_version }}
    - pyenv global {{ python_version }}
  vars:
    python_version: 3.6.4
  environment:
    PYTHON_CONFIGURE_OPTS: "--enable-shared"
    PATH: "~/.pyenv/bin:{{ ansible_env.PATH }}"
