---

- name: ensure downloaded
  stat:
    path: /usr/local/src/czmq-{{ czmq_version }}
  register: src_dir

- name: download
  become: yes
  unarchive:
    src: https://github.com/zeromq/czmq/archive/v{{ czmq_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not src_dir.stat.exists

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/czmq-{{ czmq_version }}
  with_items:
    - ./autogen.sh
    - ./configure --prefix=/usr/local/stow/czmq-{{ czmq_version }}
    - make
    - make install

- name: stow
  become: yes
  shell: stow -R czmq-{{ czmq_version }}
  args:
    chdir: /usr/local/stow
