---

- name: add yum repository
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    state: present

- name: install visual-studio-code
  become: yes
  yum:
    name: code
    state: present
