---

- name: install nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: disable site
  become: yes
  file:
    path: /etc/nginx/site-enabled/default
    state: absent
