---

- name: check if downloaded
  stat:
    path: /usr/local/src/swig-{{ swig_version }}
  register: src_dir

#
# FIXME
#
#   Failed to validate the SSL certificate for jaist.dl.sourceforge.net:443.
#   Make sure your managed systems have a valid CA certificate installed.
#   If the website serving the url uses SNI you need python >= 2.7.9
#   on your managed machine or you can install
#   the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules
#   to perform SNI verification in python >= 2.6.
#
# - name: download
#   become: yes
#   unarchive:
#     src: http://prdownloads.sourceforge.net/swig/swig-{{ swig_version }}.tar.gz
#     dest: /usr/local/src
#     remote_src: yes
#   when: not src_dir.stat.exists

- name: download
  become: yes
  shell: curl -fsSL http://prdownloads.sourceforge.net/swig/swig-{{ swig_version }}.tar.gz | tar zxv
  args:
    chdir: /usr/local/src
    warn: no
  when: not src_dir.stat.exists

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/swig-{{ swig_version }}
  with_items:
    - ./configure --prefix=/usr/local/stow/swig-{{ swig_version }}
    - make
    - make install

- name: stow
  become: yes
  shell: stow -R swig-{{ swig_version }}
  args:
    chdir: /usr/local/stow
