---

- name: install ccache
  become: yes
  yum:
    name: ccache
    state: present

- name: enable ccache
  become: yes
  file:
    src: /usr/bin/ccache
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - cc
    - c++
    - gcc
    - g++
