---

- name: ensure downloaded
  stat:
    path: /usr/local/src/googletest-release-{{ gtest_version }}
  register: src_dir

- name: download
  become: yes
  unarchive:
    src: https://github.com/google/googletest/archive/release-{{ gtest_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  when: not src_dir.stat.exists

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/googletest-release-{{ gtest_version }}
  with_items:
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/stow/gtest-{{ gtest_version }} .
    - ninja
    - ninja install

- name: stow
  become: yes
  shell: stow -R gtest-{{ gtest_version }}
  args:
    chdir: /usr/local/stow
