---

- name: download
  become: yes
  unarchive:
    src: https://github.com/google/googletest/archive/release-{{ gtest_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/googletest-release-{{ gtest_version }}

- name: compile and install
  become: yes
  shell: "{{ item }}"
  with_items:
    - cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/stow/gtest-{{ gtest_version }} .
    - ninja
    - ninja install
  args:
    chdir: /usr/local/src/googletest-release-{{ gtest_version }}
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: stow
  become: yes
  shell: stow -R gtest-{{ gtest_version }}
  args:
    chdir: /usr/local/stow
