---

- name: ensure visual-studio-code installed
  stat:
    path: ~/.local/share/umake/ide/visual-studio-code
  register: install_dir

- name: install visual-studio-code
  shell: umake ide visual-studio-code ~/.local/share/umake/ide/visual-studio-code
  when: not install_dir.stat.exists
