---

- name: install packages
  become: yes
  yum:
    name: "{{ item }}"
  with_items:
    - git2u
    - openssh-clients
    - procps-ng

- name: install git-lfs
  become: yes
  shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
  args:
    warn: no
