---

- name: add apt repository
  become: yes
  apt_repository:
    repo: 'ppa:git-core/ppa'
  register: git_repo

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - openssh-client
    - procps
  when: git_repo is changed

- name: install git-lfs
  become: yes
  shell: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  args:
    warn: no
