---

- name: download
  become: yes
  unarchive:
    src: https://github.com/zeromq/libzmq/releases/download/v{{ zmq_version }}/zeromq-{{ zmq_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/zeromq-{{ zmq_version }}

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/zeromq-{{ zmq_version }}
  with_items:
    - ./configure --prefix=/usr/local/stow/zeromq-{{ zmq_version }}
    - make
    - make install

- name: stow
  become: yes
  shell: stow -R zeromq-{{ zmq_version }}
  args:
    chdir: /usr/local/stow
