---

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - autoconf
    - automake
    - bzip2
    - dpkg-dev
    - file
    - g++-4.8
    - gcc-4.8
    - imagemagick
    - libbz2-dev
    - libc6-dev
    - libcurl4-openssl-dev
    - libdb-dev
    - libevent-dev
    - libffi-dev
    - libgdbm-dev
    - libgeoip-dev
    - libglib2.0-dev
    - libjpeg-dev
    - libkrb5-dev
    - liblzma-dev
    - libmagickcore-dev
    - libmagickwand-dev
    - libmysqlclient-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libpng-dev
    - libpq-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libwebp-dev
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - make
    - patch
    - xz-utils
    - zlib1g-dev

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libtool-bin
  when: ansible_distribution_major_version|int >= 16

- name: update alternatives
  become: yes
  alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
  with_items:
    - name: gcc
      link: /usr/bin/gcc
      path: /usr/bin/gcc-4.8
    - name: g++
      link: /usr/bin/g++
      path: /usr/bin/g++-4.8
