---

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - autoconf
    - automake
    - bzip2
    - file
    - g++
    - gcc
    - imagemagick
    - libbz2-dev
    - libc6-dev
    - libcurl4-openssl-dev
    - libdb-dev
    - libevent-dev
    - libffi-dev
    - libgeoip-dev
    - libglib2.0-dev
    - libjpeg-dev
    - libkrb5-dev
    - liblzma-dev
    - libmagickcore-dev
    - libmagickwand-dev
    - libmysqlclient-dev
    - libncurses-dev
    - libpng-dev
    - libpq-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libwebp-dev
    - libxml2-dev
    - libxslt-dev
    - libyaml-dev
    - make
    - patch
    - xz-utils
    - zlib1g-dev
