---

- name: install java
  become: yes
  yum:
    name: java-1.8.0-openjdk-devel

- name: install jenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s jenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"

- name: enable java
  shell: |
    eval "$(anyenv init -)"
    jenv add /usr/lib/jvm/java-1.8.0
    jenv global {{ java_version }}
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
