---

- name: add apt repository
  become: yes
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: install packages
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: install jenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s jenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"

- name: enable java
  shell: |
    eval "$(anyenv init -)"
    jenv add /usr/lib/jvm/java-7-openjdk-amd64
    jenv add /usr/lib/jvm/java-8-openjdk-amd64
    jenv global {{ java_version }}
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
