---

- name: add apt key
  become: yes
  apt_key:
    url: https://apt.dockerproject.org/gpg
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-trusty main
    filename: docker.list
    state: present
  register: add_apt_repo

- name: install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "{{ add_apt_repo|changed }}"
  with_items:
    - linux-image-extra-4.4.0-31-generic
    - linux-image-extra-virtual
    - docker-engine

- name: add vagrant user to docker group
  become: yes
  shell: usermod -aG docker vagrant
  when: ansible_user_id == "vagrant"
