---

- name: add rpm key
  become: yes
  rpm_key:
    state: present
    key: http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/CentOS_7/repodata/repomd.xml.key

- name: add yum repository
  become: yes
  yum_repository:
    name: zeromq
    description: Latest released versions, no DRAFT apis (CentOS_7)
    baseurl: http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/CentOS_7/

- name: install packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libzmq5
    - libczmq4
