---

- name: install guake
  become: yes
  yum:
    name: guake
    state: present

- name: enable auto start
  become: yes
  copy:
    src: /usr/share/applications/guake.desktop
    dest: /etc/xdg/autostart/guake.desktop
    remote_src: yes
