---

- name: install ndenv
  shell: |
    eval "$(anyenv init -)"
    anyenv install -s ndenv
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"

- name: install node
  shell: |
    eval "$(anyenv init -)"
    ndenv install -s {{ node_version }}
    ndenv global {{ node_version }}
  environment:
    PATH: "{{ anyenv_root }}/bin:{{ ansible_env.PATH }}"
