---

- name: download
  become: yes
  unarchive:
    src: http://fallabs.com/kyotocabinet/pkg/kyotocabinet-{{ kc_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
    creates: /usr/local/src/kyotocabinet-{{ kc_version }}

- name: compile and install
  become: yes
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/kyotocabinet-{{ kc_version }}
  with_items:
    - ./configure --prefix=/usr/local/stow/kyotocabinet-{{ kc_version }}
    - make
    - make install

- name: stow
  become: yes
  shell: stow -R kyotocabinet-{{ kc_version }}
  args:
    chdir: /usr/local/stow
